"""no canvas

Revision ID: bda659667590
Revises: e320d2dcb932
Create Date: 2026-02-26 19:22:41.227393
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bda659667590'
down_revision = 'e320d2dcb932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_connectors_project_name')
    )
    op.drop_table('edges')
    op.add_column('nodes', sa.Column('order_index', sa.Integer(), nullable=False))
    op.drop_column('nodes', 'position_x')
    op.drop_column('nodes', 'position_y')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('position_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('nodes', sa.Column('position_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('nodes', 'order_index')
    op.create_table('edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_node', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_node', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('edges_pkey')),
    sa.UniqueConstraint('rule_id', 'source_node', 'target_node', name=op.f('uq_edges_rule_src_dst'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('connectors')
    # ### end Alembic commands ###
