"""init

Revision ID: 389b3bf76691
Revises: 
Create Date: 2026-02-06 15:51:23.143562
"""
from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = '389b3bf76691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rule_id', sa.Integer(), nullable=False),
                    sa.Column('source_node', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('target_node', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('rule_id', 'source_node', 'target_node', name='uq_edges_rule_src_dst')
                    )
    op.create_table('execution_steps',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('completed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('executions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('rule_id', sa.Integer(), nullable=False),
                    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('completed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('variables', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('execution_id')
                    )
    op.create_table('global_vars',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('project_id', 'key', name='uq_globals_project_key')
                    )
    op.create_table('nodes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rule_id', sa.Integer(), nullable=False),
                    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('position_x', sa.Float(), nullable=False),
                    sa.Column('position_y', sa.Float(), nullable=False),
                    sa.Column('config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('rule_id', 'node_id', name='uq_nodes_rule_node')
                    )
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('rules',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('project_id', 'name', name='uq_rules_project_name')
                    )
    op.create_table('stored_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('rule_id', sa.Integer(), nullable=False),
                    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_data')
    op.drop_table('rules')
    op.drop_table('projects')
    op.drop_table('nodes')
    op.drop_table('global_vars')
    op.drop_table('executions')
    op.drop_table('execution_steps')
    op.drop_table('edges')
    # ### end Alembic commands ###
