"""add connectors and stored_data scope

Revision ID: e320d2dcb932
Revises: 389b3bf76691
Create Date: 2026-02-25 17:05:51.748514
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e320d2dcb932'
down_revision = '389b3bf76691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_steps', sa.Column('step_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stored_data', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stored_data', 'scope')
    op.drop_column('execution_steps', 'step_data')
    # ### end Alembic commands ###
